create routes and empty components for them
marik0201/cinema.StudentLab pull request #1
Opened 2019-03-14 10:40 UTC by marik0201

Create routes and empty route components to see site layout.
- CinemasPage (main page with cinemas, search, sorting,  etc.) "/"
- UserPage ( user page with orders, personal information) "/user"
- EditCinema (page, where admin can edit information about cinemas)    
" /admin/cinema"
- EditFilm ( page, where admin can edit information about films) " /admin/cinema"
- EditSession (page, where admin can edit information about sessions) " /admin/session"
- EditUsers (page, where admin can edit information about users) " /admin/user"
- AdminPage (main admin page) "/admin"

2019-03-15 09:39 UTC, andrei-kruhliakou-itechart requested changes
- add components with empty content for all routes, not just empty js files
- spelling error in output bundle filename ("bandle.js")
- add meaningful info in package.json: name, description, author, license

2019-03-15 09:39 UTC, andrei-kruhliakou-itechart commented on src/components/CinemasPage/CinemasPage.js
> +                hi
replace with meaningful text or remove completely

2019-03-15 09:39 UTC, andrei-kruhliakou-itechart commented on src/components/Header/style.scss
> +    -webkit-box-shadow: 2px 2px 6px 1px rgba(0,0,0,0.75);
you can you some tool like autoprefixer for automating such properties

2019-03-15 09:39 UTC, andrei-kruhliakou-itechart commented on src/components/Main/Main.js
> +import { Switch, Route } from "react-router-dom";
use logical grouping for imports:
- third party libraries
- components
- styles
- images

2019-03-18 10:11 UTC, mark-likhtar reviewed
improve all errors and and autoprefixer

2019-03-18 17:49 UTC, merged