Auth
marik0201/cinema.StudentLab pull request #7
Opened 2019-04-05 11:48 UTC by marik0201

- contains SignIn/SignUp components 
- SignIn contains login and password fields, component request on server endpoint to find user with correct information, if all ok, redirect to main page
- SignUp component contains name, login, password and repeatPassword fields and request on server to write user on database, check all errors

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart requested changes

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/Auth/Auth.js
> +              'aria-describedby': 'message-id'
What is this for?

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/Auth/style.scss
> +    0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 2px 1px -1px rgba(0, 0, 0, 0.12);
formatting

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/Header/Header.js
> +    userName ? this.setState({logIn: true, userName}) : this.setState({logIn: false})
Why are you using user name to determine if user is logged in?

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/Header/Header.js
> +    const userName = localStorage.getItem('userName');
why is the same code here as in componentWillMount() ?

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/SignUp/SignUp.js
> +    !name || !login || !password || !repeatPasswod
Simplify structure of this statement. It's very hard to follow all those ? : . It's better to use separate if statements here (Note: I'm not saying not to use ternary operator at all but you should think about code readability first)

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/LogIn/LogIn.js
> +            localStorage.setItem('userLogin', res.data.userLogin);
Why do you need to store login for?

2019-04-05 17:17 UTC, andrei-kruhliakou-itechart commented on src/components/SessionCard/SessionCard.js
> +        setTimeout(() =>
indentation

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart requested changes

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart commented on src/components/Header/Header.js
> +    anchorEl: null
What this property for? Name it properly.
Also working with DOM elements directly doesn't feel natural in React. Try to think of another approach.

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart commented on src/components/Header/Header.js
>    componentWillReceiveProps = () => {
componentWillMount and componentWillReceiveProps are both deprecated
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart commented on src/components/Header/Header.js
> +                  aria-owns={anchorEl ? 'simple-menu' : undefined}
please STOP copypasting code without understanding what it is doing!

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart commented on src/components/UserPage/UserPage.js
> +      .catch(() => {
You shouldn't catch them all, login related data should be changed only on 401

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart commented on src/components/Header/Header.js
> +    localStorage.removeItem('token');
Move all the code related to storing and retrieving auth data from local storage to a separate service class

2019-04-10 13:42 UTC, andrei-kruhliakou-itechart commented on src/components/UserPage/UserPage.js
> +      .get('http://localhost:3000/api/auth', {
What is the purpose of this call?

2019-04-16 08:35 UTC, andrei-kruhliakou-itechart requested changes

2019-04-16 08:35 UTC, andrei-kruhliakou-itechart commented on src/Service/UserService.js
> +UserService.isLoggedIn = () => {
method which name started with 'is' should return boolean value
if you need method to return a token you should create separate method and name it accordingly

2019-04-16 08:35 UTC, andrei-kruhliakou-itechart commented on src/components/SessionCard/SessionCard.js
> +    const token = localStorage.getItem('token');
use UserService method here

2019-04-16 09:52 UTC, marik0201 commented on src/components/SessionCard/SessionCard.js
> +    const token = localStorage.getItem('token');
done

2019-04-16 09:55 UTC, andrei-kruhliakou-itechart approved these changes

2019-04-16 09:55 UTC, merged